name: publish
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: MainENV
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build and publish to modrinth
        run: ./gradlew build modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

      - name: upload to github release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}